### ISSUE TITLE
Shieldy Pickup with Artifact of Command Issue

### ISSUE THREAD

**Issue by LastCoinProductions** [TufferDaze/RoR2_PoppyMod#2]
I feel like I should preface this by saying that this is a pretty unique circumstance that only impacts gameplay when an optional feature is enabled.

Shieldy drops register as yellow items and when the Artifact of Command is enabled it requires the player to physically interact with them and "choose" an item to drop before they can be picked up. This severely disrupts the flow of gameplay and makes the Shieldy drops almost unusable in this game mode.

**Comment by TufferDaze** [comment]
I initially figured that it wasn't possible to force drops with command but I'll see if I can figure something out.

**Comment by TufferDaze** [comment]
A fix has been deployed along with an update for the Seekers DLC. Do let me know if any other issues arise. :)
