### ISSUE TITLE
found some errors

### ISSUE THREAD

**Issue by mypingishuge** [TufferDaze/RoR2_PoppyMod#3]
![image](https://github.com/user-attachments/assets/dd25201a-b5ed-4437-86a2-63ff2a3911b6)

**Comment by TufferDaze** [comment]
Do you know when these errors popped up? And did they have an effect in-game?

**Comment by TufferDaze** [comment]
I've only been able to recreate these errors by buying a chest right after taking fall damage. Not sure why this is the case at the moment, but it doesn't seem to break the game in an overt way unless you've experienced something else. I've isolated the erroring code and hid the errors. I'll add this to the bug list and close this thread for now.

**Comment by mypingishuge** [comment]
Every time you picked up the shield after m2, maybe game thought it was an interactable, i see squid polyp in the error and flatitembuffs mentioned
